### your site title here

title: Kaveh Rezaei Shiraz
# description: subtitle | affiliations | motto
description: Software Engineer 


baseurl: / #name of GitHub repository
url: #custom url to be used instead of GitHub repository
email: me@kavehrs.com


highlighter: rouge
markdown: kramdown

# Blog Pagination
# paginate: 10
# permalink: /blog/:year/:title/
#paginate_path: /blog/page:num/
paginate_multiple:
  - paginate: 5
    permalink: /blog/:year/:title/
    paginate_path: '/blog/page:num/'
    sub_dir: '/blog'
  - paginate: 5
    permalink: /fa/:year/:title/
    paginate_path: '/fa/page:num/'
    sub_dir: '/fa'

    
    

# Social media links in footer
#facebook: "#"
twitter: "kavehrs"
linkedin: "kavehrs"
github: "kavehrs"
#researchgate: "#"
orcid: "0000-0001-9591-7724"


highlighter: rouge
markdown: kramdown

# Tracker
analytics: UA-189045105-2

#optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
    permalink: /projects/:path/

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
